services:
  - type: web
    name: dynastorev2-backend-111
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
